import type { ContentEntry } from "./types";

const programImages = {
  exchange: "https://static.wixstatic.com/media/d8edaa_e7b941f2c3844ddd8aedd42821c0b449~mv2.png/v1/fill/w_1400,h_900,al_c,q_90/d8edaa_e7b941f2c3844ddd8aedd42821c0b449~mv2.png",
  workshops: "https://static.wixstatic.com/media/d8edaa_bc1768cf4f164aef92f673e53fcf4336~mv2.jpg/v1/fill/w_1600,h_1000,al_c,q_90/d8edaa_bc1768cf4f164aef92f673e53fcf4336~mv2.jpg",
  performances: "https://static.wixstatic.com/media/d8edaa_96c873e7fe074781a638d1e080ca2a0b~mv2.png/v1/fit/w_2500,h_1330,al_c,q_90/d8edaa_96c873e7fe074781a638d1e080ca2a0b~mv2.png",
  mentorship: "https://static.wixstatic.com/media/d8edaa_8f163e2a9d3e466cab992bfe2ed9ed1e~mv2.png/v1/fill/w_1400,h_900,al_c,q_90/d8edaa_8f163e2a9d3e466cab992bfe2ed9ed1e~mv2.png",
};

export const defaultPrograms = [
  {
    number: "01",
    slug: "music-exchange",
    title: "Music Exchange",
    text: "Sharing sheet music, music books, and learning resources with the community.",
    description: "Music Exchange gives pre-loved scores, method books, and learning materials a new life. Youth volunteers collect, sort, catalog, and share materials with students, teachers, and community music programs.",
    impact: "Every donated book opens another door to practice, discovery, and creative confidence.",
    image: programImages.exchange,
    gallery: [programImages.exchange, programImages.workshops, programImages.mentorship],
  },
  {
    number: "02",
    slug: "free-music-workshops",
    title: "Free Music Workshops",
    text: "Making joyful, high-quality music education more accessible to every learner.",
    description: "Welcoming workshops introduce young learners to instruments, rhythm, ensemble skills, and the joy of making music together. Sessions are led by prepared youth volunteers with adult guidance.",
    impact: "Students leave with a first success, a new musical idea, and the confidence to keep exploring.",
    image: programImages.workshops,
    gallery: [programImages.workshops, programImages.mentorship, programImages.performances],
  },
  {
    number: "03",
    slug: "community-performances",
    title: "Community Performances",
    text: "Bringing live music to senior centers, schools, hospitals, and public spaces.",
    description: "Small ensembles and youth orchestras bring thoughtfully prepared performances into community spaces. Each program is designed around its audience and creates room for conversation and connection.",
    impact: "A shared performance can brighten a room, bring back a memory, and make neighbors feel seen.",
    image: programImages.performances,
    gallery: [programImages.performances, programImages.exchange, programImages.workshops],
  },
  {
    number: "04",
    slug: "youth-mentorship",
    title: "Youth Mentorship",
    text: "Young musicians helping the next generation find confidence and grow.",
    description: "Experienced student musicians support younger learners through demonstrations, guided practice, encouragement, and honest conversations about the work behind musical growth.",
    impact: "Mentorship builds skill in both directions—young learners gain confidence while youth leaders learn to listen, explain, and serve.",
    image: programImages.mentorship,
    gallery: [programImages.mentorship, programImages.workshops, programImages.performances],
  },
];

type DefaultRow = readonly [string, string, string, string, string];

export const editableContentDefaults: DefaultRow[] = [
  ["site.name", "Inspire With Music", "Global", "Site name", "text"],
  ["site.organization", "Ivy Chamber Strings", "Global", "Legal organization name", "text"],
  ["site.logo_url", "", "Global", "Logo image", "image"],
  ["home.hero_eyebrow", "YOUTH-LED · MUSIC-DRIVEN · COMMUNITY-FOCUSED", "Homepage", "Hero eyebrow", "text"],
  ["home.hero_title", "Music in Action. Youth in Service.", "Homepage", "Hero headline", "text"],
  ["home.hero_text", "Empowering young musicians to share their talents, serve their communities, and make a difference through music.", "Homepage", "Hero supporting text", "textarea"],
  ["home.hero_image", "", "Homepage", "Hero image", "image"],
  ["home.who_title", "We turn a passion for music into meaningful service.", "Homepage", "Who we are heading", "text"],
  ["home.who_body", "Ivy Chamber Strings is a youth-led nonprofit creating opportunities for young people to lead, connect, and make a difference through performance, education, mentorship, and community outreach.", "Homepage", "Who we are body", "textarea"],
  ["home.story_title", "Every note has led us here.", "Homepage", "Story heading", "text"],
  ["home.story_body", "From serving our local communities to connecting with audiences around the world, our journey has been shaped by music, service, and a growing community of young musicians.", "Homepage", "Story summary", "textarea"],
  ["home.story_timeline_json", JSON.stringify([{title:"2019",label:"IT BEGINS"},{title:"EARLY YEARS",label:"SERVING OUR COMMUNITY"},{title:"GROWING",label:"YOUTH-LED IMPACT"},{title:"TODAY",label:"MUSIC BEYOND BORDERS"}]), "Homepage", "Story timeline (JSON list)", "textarea"],
  ["home.leaders_json", "[]", "Homepage", "Youth leaders (JSON list)", "textarea"],
  ["home.services_json", "[{\"title\":\"PERFORM\",\"text\":\"Bringing music into our communities.\",\"icon\":\"♩\"},{\"title\":\"TEACH\",\"text\":\"Sharing music through lessons and workshops.\",\"icon\":\"♫\"},{\"title\":\"MENTOR\",\"text\":\"Helping young musicians learn and grow.\",\"icon\":\"♬\"},{\"title\":\"SERVE\",\"text\":\"Giving back through music and community projects.\",\"icon\":\"♪\"}]", "Homepage", "What we do cards (JSON list)", "textarea"],
  ["home.impact_title", "A growing community.", "Homepage", "Impact heading", "text"],
  ["home.impact_accent", "A lasting echo.", "Homepage", "Impact highlighted heading", "text"],
  ["home.impact_body", "Behind every number is a story of young musicians sharing their time, talent, and love of music with the community.", "Homepage", "Impact introduction", "textarea"],
  ["home.join_title", "Your talent can change the tempo.", "Homepage", "Join heading", "text"],
  ["about.hero_title", "A love of music. A call to serve.", "About", "Page headline", "text"],
  ["about.hero_text", "We believe young people are not only future leaders—they are powerful leaders right now.", "About", "Page introduction", "textarea"],
  ["about.mission", "We make space for young musicians to lead with heart.", "About", "Mission heading", "text"],
  ["about.body", "Ivy Chamber Strings is a 501(c)(3) nonprofit youth orchestra and chamber music program serving students ages 6 to 17 in Orange County. We connect musical growth with purposeful service.", "About", "Mission body", "textarea"],
  ["volunteers.hero_title", "Many instruments. One shared purpose.", "Volunteers", "Page headline", "text"],
  ["volunteers.hero_text", "Meet the young people turning rehearsal-room discipline into real-world compassion.", "Volunteers", "Page introduction", "textarea"],
  ["programs.hero_title", "Music that moves into the world.", "Programs", "Page headline", "text"],
  ["programs.hero_text", "Four youth-led programs. Countless ways to connect.", "Programs", "Page introduction", "textarea"],
  ["programs.items_json", JSON.stringify(defaultPrograms), "Programs", "Programs, details, and image galleries", "programs"],
  ["stories.hero_title", "The moments between the notes.", "Stories", "Page headline", "text"],
  ["stories.hero_text", "Student-written stories, photos, and reflections from a community in motion.", "Stories", "Page introduction", "textarea"],
  ["impact.hero_title", "What service sounds like.", "Impact", "Page headline", "text"],
  ["impact.hero_text", "Hours are part of the story. People, confidence, connection, and access complete it.", "Impact", "Page introduction", "textarea"],
  ["impact.section_title", "A growing community. A lasting echo.", "Impact", "Impact section heading", "text"],
  ["impact.section_body", "Behind every number is a story of young musicians sharing their time, talent, and love of music with the community.", "Impact", "Impact section introduction", "textarea"],
  ["impact.volunteers", "120", "Impact", "Youth volunteers", "number"],
  ["impact.hours", "3800", "Impact", "Service hours", "number"],
  ["impact.events", "86", "Impact", "Community events", "number"],
  ["impact.people", "12000", "Impact", "People reached", "number"],
  ["impact.music_shared", "XXX", "Impact", "Music shared", "text"],
  ["join.hero_title", "Bring what you love. Leave an echo.", "Join", "Page headline", "text"],
  ["join.hero_text", "Volunteer, partner, or bring a program to your community. Your next step starts here.", "Join", "Page introduction", "textarea"],
  ["donate.hero_title", "Help the next generation be heard.", "Donate", "Page headline", "text"],
  ["donate.hero_text", "Your support helps us expand youth-led music programs, community performances, educational opportunities, and access to music.", "Donate", "Page introduction", "textarea"],
  ["donate.zelle", "Add verified Zelle information", "Donate", "Zelle information", "textarea"],
  ["donate.paypal_url", "", "Donate", "PayPal donation URL", "url"],
  ["donate.materials_url", "", "Donate", "Music materials form URL", "url"],
  ["footer.contact_email", "hello@inspirewithmusic.org", "Footer", "Contact email", "email"],
  ["footer.instagram_url", "", "Footer", "Instagram URL", "url"],
  ["footer.youtube_url", "", "Footer", "YouTube URL", "url"],
];

export const defaultContentEntries: ContentEntry[] = editableContentDefaults.map(([key,value,page,label,field_type]) => ({
  key,
  value,
  page,
  label,
  field_type,
  updated_at: "",
}));

export const defaultContentMap = Object.fromEntries(defaultContentEntries.map(entry => [entry.key, entry.value]));
